source 'https://github.com/kksys/CocoaPodsSpecs.git'

# plugin 'cocoapods-binary'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

abstract_target 'iOS' do
  platform :ios, '15.0'

  target 'Example - iOS' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    all_binary!

    # Pods for Example
    pod 'Chronometer', '>=0.0.3'

    target 'ExampleTests - iOS' do
      inherit! :search_paths
      # Pods for testing
    end

    target 'ExampleUITests - iOS' do
      # Pods for testing
    end
  end
end

abstract_target 'macOS' do
  platform :osx, '12.0'

  target 'Example - macOS' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    all_binary!
     
    # Pods for Example
    pod 'Chronometer', '>=0.0.3'
     
    target 'ExampleTests - macOS' do
      inherit! :search_paths
      # Pods for testing
    end

    target 'ExampleUITests - macOS' do
      # Pods for testing
    end

    target 'Screenshot' do
    end
  end
end
