source 'https://github.com/kksys/CocoaPodsSpecs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS' do
  platform :ios, '15.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'Chronograph', '0.0.4-alpha0'

  target 'iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSUITests' do
    # Pods for testing
  end
end

target 'macOS' do
  platform :osx, '12.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    
  # Pods for Example
  pod 'Chronograph', '0.0.4-alpha0'
    
  target 'macOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'macOSUITests' do
    # Pods for testing
  end

  target 'Screenshot' do
    # Pods for screenshot
  end
end
